package com.lexAbogado.notaria.dato.entity;
// Generated 08-11-2018 0:07:03 by Hibernate Tools 4.3.1


import java.math.BigDecimal;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * Categoria generated by hbm2java
 */
@Entity
@Table(name="CATEGORIA"
    ,schema="DUOC_USER2"
)
public class Categoria  implements java.io.Serializable {


     private BigDecimal idCategoria;
     private String nomCategoria;
     private Set tramites = new HashSet(0);

    public Categoria() {
    }

	
    public Categoria(BigDecimal idCategoria) {
        this.idCategoria = idCategoria;
    }
    public Categoria(BigDecimal idCategoria, String nomCategoria, Set tramites) {
       this.idCategoria = idCategoria;
       this.nomCategoria = nomCategoria;
       this.tramites = tramites;
    }
   
     @Id 

    
    @Column(name="ID_CATEGORIA", unique=true, nullable=false, precision=22, scale=0)
    public BigDecimal getIdCategoria() {
        return this.idCategoria;
    }
    
    public void setIdCategoria(BigDecimal idCategoria) {
        this.idCategoria = idCategoria;
    }

    
    @Column(name="NOM_CATEGORIA", length=4000)
    public String getNomCategoria() {
        return this.nomCategoria;
    }
    
    public void setNomCategoria(String nomCategoria) {
        this.nomCategoria = nomCategoria;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="categoria")
    public Set getTramites() {
        return this.tramites;
    }
    
    public void setTramites(Set tramites) {
        this.tramites = tramites;
    }




}


