package com.lexAbogado.notaria.dato.entity;
// Generated 08-11-2018 0:07:03 by Hibernate Tools 4.3.1


import java.math.BigDecimal;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * EstadoTramite generated by hbm2java
 */
@Entity
@Table(name="ESTADO_TRAMITE"
    ,schema="DUOC_USER2"
)
public class EstadoTramite  implements java.io.Serializable {


     private BigDecimal idStdTrmt;
     private String nombreStdTrmt;
     private Set historialTramites = new HashSet(0);

    public EstadoTramite() {
    }

	
    public EstadoTramite(BigDecimal idStdTrmt) {
        this.idStdTrmt = idStdTrmt;
    }
    public EstadoTramite(BigDecimal idStdTrmt, String nombreStdTrmt, Set historialTramites) {
       this.idStdTrmt = idStdTrmt;
       this.nombreStdTrmt = nombreStdTrmt;
       this.historialTramites = historialTramites;
    }
   
     @Id 

    
    @Column(name="ID_STD_TRMT", unique=true, nullable=false, precision=22, scale=0)
    public BigDecimal getIdStdTrmt() {
        return this.idStdTrmt;
    }
    
    public void setIdStdTrmt(BigDecimal idStdTrmt) {
        this.idStdTrmt = idStdTrmt;
    }

    
    @Column(name="NOMBRE_STD_TRMT", length=4000)
    public String getNombreStdTrmt() {
        return this.nombreStdTrmt;
    }
    
    public void setNombreStdTrmt(String nombreStdTrmt) {
        this.nombreStdTrmt = nombreStdTrmt;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="estadoTramite")
    public Set getHistorialTramites() {
        return this.historialTramites;
    }
    
    public void setHistorialTramites(Set historialTramites) {
        this.historialTramites = historialTramites;
    }




}


