package com.lexAbogado.notaria.dato.entity;
// Generated 08-11-2018 0:07:03 by Hibernate Tools 4.3.1


import java.math.BigDecimal;
import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * HistorialTramite generated by hbm2java
 */
@Entity
@Table(name="HISTORIAL_TRAMITE"
    ,schema="DUOC_USER2"
)
public class HistorialTramite  implements java.io.Serializable {


     private BigDecimal idHstrltrmt;
     private Cliente cliente;
     private Convenio convenio;
     private EstadoTramite estadoTramite;
     private Tramite tramite;
     private Date fchCrcnHstrltrmt;
     private Date fchJcnHstrltrmt;
     private Date fchCrrHstrltrmt;

    public HistorialTramite() {
    }

	
    public HistorialTramite(BigDecimal idHstrltrmt) {
        this.idHstrltrmt = idHstrltrmt;
    }
    public HistorialTramite(BigDecimal idHstrltrmt, Cliente cliente, Convenio convenio, EstadoTramite estadoTramite, Tramite tramite, Date fchCrcnHstrltrmt, Date fchJcnHstrltrmt, Date fchCrrHstrltrmt) {
       this.idHstrltrmt = idHstrltrmt;
       this.cliente = cliente;
       this.convenio = convenio;
       this.estadoTramite = estadoTramite;
       this.tramite = tramite;
       this.fchCrcnHstrltrmt = fchCrcnHstrltrmt;
       this.fchJcnHstrltrmt = fchJcnHstrltrmt;
       this.fchCrrHstrltrmt = fchCrrHstrltrmt;
    }
   
     @Id 

    
    @Column(name="ID_HSTRLTRMT", unique=true, nullable=false, precision=22, scale=0)
    public BigDecimal getIdHstrltrmt() {
        return this.idHstrltrmt;
    }
    
    public void setIdHstrltrmt(BigDecimal idHstrltrmt) {
        this.idHstrltrmt = idHstrltrmt;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="ID_CLNT")
    public Cliente getCliente() {
        return this.cliente;
    }
    
    public void setCliente(Cliente cliente) {
        this.cliente = cliente;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="ID_CNVN")
    public Convenio getConvenio() {
        return this.convenio;
    }
    
    public void setConvenio(Convenio convenio) {
        this.convenio = convenio;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="ID_STD_TRMT")
    public EstadoTramite getEstadoTramite() {
        return this.estadoTramite;
    }
    
    public void setEstadoTramite(EstadoTramite estadoTramite) {
        this.estadoTramite = estadoTramite;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="ID_TRMT")
    public Tramite getTramite() {
        return this.tramite;
    }
    
    public void setTramite(Tramite tramite) {
        this.tramite = tramite;
    }

    @Temporal(TemporalType.DATE)
    @Column(name="FCH_CRCN_HSTRLTRMT", length=7)
    public Date getFchCrcnHstrltrmt() {
        return this.fchCrcnHstrltrmt;
    }
    
    public void setFchCrcnHstrltrmt(Date fchCrcnHstrltrmt) {
        this.fchCrcnHstrltrmt = fchCrcnHstrltrmt;
    }

    @Temporal(TemporalType.DATE)
    @Column(name="FCH_JCN_HSTRLTRMT", length=7)
    public Date getFchJcnHstrltrmt() {
        return this.fchJcnHstrltrmt;
    }
    
    public void setFchJcnHstrltrmt(Date fchJcnHstrltrmt) {
        this.fchJcnHstrltrmt = fchJcnHstrltrmt;
    }

    @Temporal(TemporalType.DATE)
    @Column(name="FCH_CRR_HSTRLTRMT", length=7)
    public Date getFchCrrHstrltrmt() {
        return this.fchCrrHstrltrmt;
    }
    
    public void setFchCrrHstrltrmt(Date fchCrrHstrltrmt) {
        this.fchCrrHstrltrmt = fchCrrHstrltrmt;
    }




}


