package com.lexAbogado.notaria.dato.entity;
// Generated 10-11-2018 16:57:46 by Hibernate Tools 4.3.1


import java.math.BigDecimal;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * NotariaEstadoTramite generated by hbm2java
 */
@Entity
@Table(name="NOTARIA_ESTADO_TRAMITE"
    ,schema="DUOC_USER2"
)
public class NotariaEstadoTramite  implements java.io.Serializable {


     private BigDecimal idStdTrmt;
     private String nombreStdTrmt;
     private Set notariaHistorialTramites = new HashSet(0);

    public NotariaEstadoTramite() {
    }

	
    public NotariaEstadoTramite(BigDecimal idStdTrmt) {
        this.idStdTrmt = idStdTrmt;
    }
    public NotariaEstadoTramite(BigDecimal idStdTrmt, String nombreStdTrmt, Set notariaHistorialTramites) {
       this.idStdTrmt = idStdTrmt;
       this.nombreStdTrmt = nombreStdTrmt;
       this.notariaHistorialTramites = notariaHistorialTramites;
    }
   
     @Id 

    
    @Column(name="ID_STD_TRMT", unique=true, nullable=false, precision=22, scale=0)
    public BigDecimal getIdStdTrmt() {
        return this.idStdTrmt;
    }
    
    public void setIdStdTrmt(BigDecimal idStdTrmt) {
        this.idStdTrmt = idStdTrmt;
    }

    
    @Column(name="NOMBRE_STD_TRMT", length=4000)
    public String getNombreStdTrmt() {
        return this.nombreStdTrmt;
    }
    
    public void setNombreStdTrmt(String nombreStdTrmt) {
        this.nombreStdTrmt = nombreStdTrmt;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="notariaEstadoTramite")
    public Set getNotariaHistorialTramites() {
        return this.notariaHistorialTramites;
    }
    
    public void setNotariaHistorialTramites(Set notariaHistorialTramites) {
        this.notariaHistorialTramites = notariaHistorialTramites;
    }




}


