package com.lexAbogado.notaria.dato.entity;
// Generated 10-11-2018 9:00:34 by Hibernate Tools 4.3.1


import java.math.BigDecimal;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * NotariaCliente generated by hbm2java
 */
@Entity
@Table(name="NOTARIA_CLIENTE"
    ,schema="DUOC_USER2"
)
public class NotariaCliente  implements java.io.Serializable {


     private BigDecimal idClnt;
     private BigDecimal rutClnt;
     private BigDecimal digitoRutClnt;
     private String nombre;
     private String apellido;
     private Set notariaHistorialTramites = new HashSet(0);

    public NotariaCliente() {
    }

	
    public NotariaCliente(BigDecimal idClnt) {
        this.idClnt = idClnt;
    }
    public NotariaCliente(BigDecimal idClnt, BigDecimal rutClnt, BigDecimal digitoRutClnt, String nombre, String apellido, Set notariaHistorialTramites) {
       this.idClnt = idClnt;
       this.rutClnt = rutClnt;
       this.digitoRutClnt = digitoRutClnt;
       this.nombre = nombre;
       this.apellido = apellido;
       this.notariaHistorialTramites = notariaHistorialTramites;
    }
   
     @Id 

    
    @Column(name="ID_CLNT", unique=true, nullable=false, precision=22, scale=0)
    public BigDecimal getIdClnt() {
        return this.idClnt;
    }
    
    public void setIdClnt(BigDecimal idClnt) {
        this.idClnt = idClnt;
    }

    
    @Column(name="RUT_CLNT", precision=22, scale=0)
    public BigDecimal getRutClnt() {
        return this.rutClnt;
    }
    
    public void setRutClnt(BigDecimal rutClnt) {
        this.rutClnt = rutClnt;
    }

    
    @Column(name="DIGITO_RUT_CLNT", precision=22, scale=0)
    public BigDecimal getDigitoRutClnt() {
        return this.digitoRutClnt;
    }
    
    public void setDigitoRutClnt(BigDecimal digitoRutClnt) {
        this.digitoRutClnt = digitoRutClnt;
    }

    
    @Column(name="NOMBRE", length=4000)
    public String getNombre() {
        return this.nombre;
    }
    
    public void setNombre(String nombre) {
        this.nombre = nombre;
    }

    
    @Column(name="APELLIDO", length=4000)
    public String getApellido() {
        return this.apellido;
    }
    
    public void setApellido(String apellido) {
        this.apellido = apellido;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="notariaCliente")
    public Set getNotariaHistorialTramites() {
        return this.notariaHistorialTramites;
    }
    
    public void setNotariaHistorialTramites(Set notariaHistorialTramites) {
        this.notariaHistorialTramites = notariaHistorialTramites;
    }




}


