package com.lexAbogado.notaria.dato.entity;
// Generated 10-11-2018 16:57:46 by Hibernate Tools 4.3.1


import java.math.BigDecimal;
import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * NotariaHistorialTramite generated by hbm2java
 */
@Entity
@Table(name="NOTARIA_HISTORIAL_TRAMITE"
    ,schema="DUOC_USER2"
)
public class NotariaHistorialTramite  implements java.io.Serializable {


     private BigDecimal idHstrltrmt;
     private NotariaCliente notariaCliente;
     private NotariaConvenio notariaConvenio;
     private NotariaEstadoTramite notariaEstadoTramite;
     private NotariaTramite notariaTramite;
     private Date fchCrcnHstrltrmt;
     private Date fchJcnHstrltrmt;
     private Date fchCrrHstrltrmt;

    public NotariaHistorialTramite() {
    }

	
    public NotariaHistorialTramite(BigDecimal idHstrltrmt, NotariaCliente notariaCliente, NotariaConvenio notariaConvenio, NotariaEstadoTramite notariaEstadoTramite, NotariaTramite notariaTramite) {
        this.idHstrltrmt = idHstrltrmt;
        this.notariaCliente = notariaCliente;
        this.notariaConvenio = notariaConvenio;
        this.notariaEstadoTramite = notariaEstadoTramite;
        this.notariaTramite = notariaTramite;
    }
    public NotariaHistorialTramite(BigDecimal idHstrltrmt, NotariaCliente notariaCliente, NotariaConvenio notariaConvenio, NotariaEstadoTramite notariaEstadoTramite, NotariaTramite notariaTramite, Date fchCrcnHstrltrmt, Date fchJcnHstrltrmt, Date fchCrrHstrltrmt) {
       this.idHstrltrmt = idHstrltrmt;
       this.notariaCliente = notariaCliente;
       this.notariaConvenio = notariaConvenio;
       this.notariaEstadoTramite = notariaEstadoTramite;
       this.notariaTramite = notariaTramite;
       this.fchCrcnHstrltrmt = fchCrcnHstrltrmt;
       this.fchJcnHstrltrmt = fchJcnHstrltrmt;
       this.fchCrrHstrltrmt = fchCrrHstrltrmt;
    }
   
     @Id 

    
    @Column(name="ID_HSTRLTRMT", unique=true, nullable=false, precision=22, scale=0)
    public BigDecimal getIdHstrltrmt() {
        return this.idHstrltrmt;
    }
    
    public void setIdHstrltrmt(BigDecimal idHstrltrmt) {
        this.idHstrltrmt = idHstrltrmt;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="ID_CLNT", nullable=false)
    public NotariaCliente getNotariaCliente() {
        return this.notariaCliente;
    }
    
    public void setNotariaCliente(NotariaCliente notariaCliente) {
        this.notariaCliente = notariaCliente;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="ID_CNVN", nullable=false)
    public NotariaConvenio getNotariaConvenio() {
        return this.notariaConvenio;
    }
    
    public void setNotariaConvenio(NotariaConvenio notariaConvenio) {
        this.notariaConvenio = notariaConvenio;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="ID_STD_TRMT", nullable=false)
    public NotariaEstadoTramite getNotariaEstadoTramite() {
        return this.notariaEstadoTramite;
    }
    
    public void setNotariaEstadoTramite(NotariaEstadoTramite notariaEstadoTramite) {
        this.notariaEstadoTramite = notariaEstadoTramite;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="ID_TRMT", nullable=false)
    public NotariaTramite getNotariaTramite() {
        return this.notariaTramite;
    }
    
    public void setNotariaTramite(NotariaTramite notariaTramite) {
        this.notariaTramite = notariaTramite;
    }

    @Temporal(TemporalType.DATE)
    @Column(name="FCH_CRCN_HSTRLTRMT", length=7)
    public Date getFchCrcnHstrltrmt() {
        return this.fchCrcnHstrltrmt;
    }
    
    public void setFchCrcnHstrltrmt(Date fchCrcnHstrltrmt) {
        this.fchCrcnHstrltrmt = fchCrcnHstrltrmt;
    }

    @Temporal(TemporalType.DATE)
    @Column(name="FCH_JCN_HSTRLTRMT", length=7)
    public Date getFchJcnHstrltrmt() {
        return this.fchJcnHstrltrmt;
    }
    
    public void setFchJcnHstrltrmt(Date fchJcnHstrltrmt) {
        this.fchJcnHstrltrmt = fchJcnHstrltrmt;
    }

    @Temporal(TemporalType.DATE)
    @Column(name="FCH_CRR_HSTRLTRMT", length=7)
    public Date getFchCrrHstrltrmt() {
        return this.fchCrrHstrltrmt;
    }
    
    public void setFchCrrHstrltrmt(Date fchCrrHstrltrmt) {
        this.fchCrrHstrltrmt = fchCrrHstrltrmt;
    }




}


