package com.lexAbogado.notaria.dato.entity;
// Generated 10-11-2018 9:00:34 by Hibernate Tools 4.3.1


import java.math.BigDecimal;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * NotariaConvenio generated by hbm2java
 */
@Entity
@Table(name="NOTARIA_CONVENIO"
    ,schema="DUOC_USER2"
)
public class NotariaConvenio  implements java.io.Serializable {


     private BigDecimal idCnvn;
     private String nombreCnvn;
     private BigDecimal descCnvn;
     private Set notariaHistorialTramites = new HashSet(0);

    public NotariaConvenio() {
    }

	
    public NotariaConvenio(BigDecimal idCnvn) {
        this.idCnvn = idCnvn;
    }
    public NotariaConvenio(BigDecimal idCnvn, String nombreCnvn, BigDecimal descCnvn, Set notariaHistorialTramites) {
       this.idCnvn = idCnvn;
       this.nombreCnvn = nombreCnvn;
       this.descCnvn = descCnvn;
       this.notariaHistorialTramites = notariaHistorialTramites;
    }
   
     @Id 

    
    @Column(name="ID_CNVN", unique=true, nullable=false, precision=22, scale=0)
    public BigDecimal getIdCnvn() {
        return this.idCnvn;
    }
    
    public void setIdCnvn(BigDecimal idCnvn) {
        this.idCnvn = idCnvn;
    }

    
    @Column(name="NOMBRE_CNVN", length=4000)
    public String getNombreCnvn() {
        return this.nombreCnvn;
    }
    
    public void setNombreCnvn(String nombreCnvn) {
        this.nombreCnvn = nombreCnvn;
    }

    
    @Column(name="DESC_CNVN", precision=22, scale=0)
    public BigDecimal getDescCnvn() {
        return this.descCnvn;
    }
    
    public void setDescCnvn(BigDecimal descCnvn) {
        this.descCnvn = descCnvn;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="notariaConvenio")
    public Set getNotariaHistorialTramites() {
        return this.notariaHistorialTramites;
    }
    
    public void setNotariaHistorialTramites(Set notariaHistorialTramites) {
        this.notariaHistorialTramites = notariaHistorialTramites;
    }




}


