package com.lexAbogado.notaria.dato.entity;
// Generated 08-11-2018 0:07:03 by Hibernate Tools 4.3.1


import java.math.BigDecimal;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * Tramite generated by hbm2java
 */
@Entity
@Table(name="TRAMITE"
    ,schema="DUOC_USER2"
)
public class Tramite  implements java.io.Serializable {


     private BigDecimal idTrmt;
     private Categoria categoria;
     private Valor valor;
     private String nombreTrmt;
     private Set historialTramites = new HashSet(0);

    public Tramite() {
    }

	
    public Tramite(BigDecimal idTrmt) {
        this.idTrmt = idTrmt;
    }
    public Tramite(BigDecimal idTrmt, Categoria categoria, Valor valor, String nombreTrmt, Set historialTramites) {
       this.idTrmt = idTrmt;
       this.categoria = categoria;
       this.valor = valor;
       this.nombreTrmt = nombreTrmt;
       this.historialTramites = historialTramites;
    }
   
     @Id 

    
    @Column(name="ID_TRMT", unique=true, nullable=false, precision=22, scale=0)
    public BigDecimal getIdTrmt() {
        return this.idTrmt;
    }
    
    public void setIdTrmt(BigDecimal idTrmt) {
        this.idTrmt = idTrmt;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="CATEGORIA_ID_CATEGORIA")
    public Categoria getCategoria() {
        return this.categoria;
    }
    
    public void setCategoria(Categoria categoria) {
        this.categoria = categoria;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="VALOR_ID_VLR")
    public Valor getValor() {
        return this.valor;
    }
    
    public void setValor(Valor valor) {
        this.valor = valor;
    }

    
    @Column(name="NOMBRE_TRMT", length=4000)
    public String getNombreTrmt() {
        return this.nombreTrmt;
    }
    
    public void setNombreTrmt(String nombreTrmt) {
        this.nombreTrmt = nombreTrmt;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="tramite")
    public Set getHistorialTramites() {
        return this.historialTramites;
    }
    
    public void setHistorialTramites(Set historialTramites) {
        this.historialTramites = historialTramites;
    }




}


